# Generated by Django 4.0.2 on 2022-03-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_controlboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant', models.CharField(max_length=20)),
                ('nhiet_do', models.IntegerField()),
                ('do_am', models.IntegerField()),
                ('anh_sang', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='controlboard',
            old_name='brightness',
            new_name='Brightness',
        ),
    ]
